services:
  php:
    image: myapp_php:latest
    ports:
      - "8000:80"
      - "3000:3000"
    volumes:
      - ./laravel:/var/www/html:rw,cached
      - ./laravel/config/apache.conf:/etc/apache2/sites-available/000-default.conf
      - /var/www/html/node_modules
      - /var/www/html/public/build
      - /var/www/html/vendor
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      labels:
        - "com.docker.stack.namespace=swarm"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'clinica'
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      labels:
        - "com.docker.stack.namespace=swarm"

volumes:
  db-data:

networks:
  app-network:
    driver: overlay
    attachable: true
